### ISSUE TITLE
is "command structure" an infobox? if so, why didn't we find it?

### ISSUE THREAD

**Issue by sfelshin** [infolab-csail/WikipediaBase#147] opened 2016-01-18 17:49 UTC
See https://en.wikipedia.org/wiki/104th_Infantry_Division_%28United_States%29.  Note that the source contains

```
{{command structure
|name=104th Infantry Division ''"Timberwolves"''
|date=1942–1945
|parent=104th Infantry Division
...
```

When I try `get-classes` on this symbol, the only infobox class is `wikipedia-military-unit`. When I try `get-attributes` of that, I don't see anything matching `parent`. If `command structure` is an infobox, why didn't we find it and its contents? And if it isn't an infobox, what is it, how many more sorts of things like this are there, and are they common enough, and do they contain enough useful stuff, to make it worth figuring out how to find and interpret them?

**Comment by alvaromorales** [comment] 2016-02-03 20:27
Duplicate of #49

**Closed by alvaromorales** 2016-02-03 20:27 UTC
Labels: enhancement
